# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9974c110c9ddf875dbde99fe25ca9244"
name = "cart-extention"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "checkouttestdev.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
